version: '3.7'

services:
  db:
    container_name: mongoPoke
    image: mongo:latest
    restart: always
    volumes:
      - ./pokeData:/data/db
    environment: 
      - MONGO_INITDB_DATABASE= Pokemon
    ports: 
      - 27017:27017